name: Top-Languages Readme

on:
    workflow_dispatch:
    schedule:
        # Runs at 15:20 UTC
        - cron: '20 15 * * *'

permissions:
    contents: write

jobs:
    update-readme:
        name: Update this repo's README
        runs-on: ubuntu-latest
        steps:
        - name: Extract branch name
          if: github.event_name != 'pull_request'
          shell: bash
          run: |
            echo "##[set-output name=BRANCH_NAME;]$(echo ${GITHUB_REF#refs/heads/})"

        - name: Generate and update README
          uses: stephanoskomnenos/top-languages-readme@master
          with:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            BRANCH_NAME: ${{ env.BRANCH_NAME }}
